stages:
  - publish

publish:
  image: node:16
  stage: publish
  tags:
    - moreillon
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm publish --access=public
